import { createFileRoute } from "@tanstack/react-router";
import { LegalPage } from "@/components/legal-page";

export const Route = createFileRoute("/privacy-policy")({
  head: () => ({ meta: [
    { title: "Privacy Policy | HATFLOW" },
    { name: "description", content: "Learn how Hatflow collects, uses, stores and protects your personal and business information." },
    { property: "og:title", content: "Privacy Policy | HATFLOW" },
    { property: "og:description", content: "Learn how Hatflow collects, uses, stores and protects your personal and business information." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary" },
  ]}),
  component: PrivacyPagePage,
});

function PrivacyPagePage() { return <LegalPage title="Privacy Policy"><p>This Privacy Policy explains how Hatflow, a product by UnknownHat Agency ("we", "us"), collects, uses and protects information when you use our website and the Hatflow platform.</p><h2>1. Information we collect</h2><ul><li><strong>Account information:</strong> name, business name, email, phone number and login details.</li><li><strong>Business data:</strong> contacts, messages, templates, flows and CRM records you upload or create.</li><li><strong>Billing information:</strong> plan, invoices and payment status (card details are handled by payment gateways, not stored by us).</li><li><strong>Usage data:</strong> device, browser, IP address, pages visited and feature usage.</li></ul><h2>2. How we use information</h2><ul><li>To provide, operate and maintain the Hatflow platform</li><li>To connect and send messages through the WhatsApp Business API</li><li>To process payments and send service notifications</li><li>To provide support and improve our product</li><li>To detect fraud, abuse and security issues</li></ul><h2>3. Your customers' data</h2><p>You remain the owner of your contacts and conversation data. We process it only on your instructions to deliver the service. You are responsible for obtaining the necessary opt-ins from your customers as required by WhatsApp and applicable laws.</p><h2>4. Sharing with third parties</h2><p>We share data only with providers required to run the service, such as Meta (WhatsApp), hosting, payment gateways and integrations you choose to connect. We do not sell personal information.</p><h2>5. Data security</h2><p>We use reasonable technical and organisational safeguards, including encrypted connections and access controls, to protect your data.</p><h2>6. Data retention</h2><p>We retain data while your account is active and as needed for legal, tax or dispute purposes. You may request deletion of your account data.</p><h2>7. Your rights</h2><p>You can request access, correction, export or deletion of your personal information by contacting us.</p><h2>8. Cookies</h2><p>Our website uses essential and analytics cookies to function and understand usage. You can control cookies in your browser settings.</p><h2>9. Changes</h2><p>We may update this policy from time to time. Updates will be posted on this page with a new date.</p><h2>10. Contact</h2><a className="legal-contact" href="https://wa.me/917055481738?text=Hello%2C%20UnknownHat%20Team!" target="_blank" rel="noreferrer">Chat with us on WhatsApp: +91 70554 81738</a></LegalPage>; }
