/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundReturnPolicyRouteImport } from './routes/refund-return-policy'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundReturnPolicyRoute = RefundReturnPolicyRouteImport.update({
  id: '/refund-return-policy',
  path: '/refund-return-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-return-policy': typeof RefundReturnPolicyRoute
  '/support': typeof SupportRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-return-policy': typeof RefundReturnPolicyRoute
  '/support': typeof SupportRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-return-policy': typeof RefundReturnPolicyRoute
  '/support': typeof SupportRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/disclaimer'
    | '/privacy-policy'
    | '/refund-return-policy'
    | '/support'
    | '/terms-and-conditions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/disclaimer'
    | '/privacy-policy'
    | '/refund-return-policy'
    | '/support'
    | '/terms-and-conditions'
  id:
    | '__root__'
    | '/'
    | '/disclaimer'
    | '/privacy-policy'
    | '/refund-return-policy'
    | '/support'
    | '/terms-and-conditions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundReturnPolicyRoute: typeof RefundReturnPolicyRoute
  SupportRoute: typeof SupportRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-return-policy': {
      id: '/refund-return-policy'
      path: '/refund-return-policy'
      fullPath: '/refund-return-policy'
      preLoaderRoute: typeof RefundReturnPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundReturnPolicyRoute: RefundReturnPolicyRoute,
  SupportRoute: SupportRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
