/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundReturnPolicyRouteImport } from './routes/refund-return-policy'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundReturnPolicyRoute = RefundReturnPolicyRouteImport.update({
  id: '/refund-return-policy',
  path: '/refund-return-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crm': typeof CrmRoute
  '/disclaimer': typeof DisclaimerRoute
  '/features': typeof FeaturesRoute
  '/integrations': typeof IntegrationsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-return-policy': typeof RefundReturnPolicyRoute
  '/solutions': typeof SolutionsRoute
  '/support': typeof SupportRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crm': typeof CrmRoute
  '/disclaimer': typeof DisclaimerRoute
  '/features': typeof FeaturesRoute
  '/integrations': typeof IntegrationsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-return-policy': typeof RefundReturnPolicyRoute
  '/solutions': typeof SolutionsRoute
  '/support': typeof SupportRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crm': typeof CrmRoute
  '/disclaimer': typeof DisclaimerRoute
  '/features': typeof FeaturesRoute
  '/integrations': typeof IntegrationsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-return-policy': typeof RefundReturnPolicyRoute
  '/solutions': typeof SolutionsRoute
  '/support': typeof SupportRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crm'
    | '/disclaimer'
    | '/features'
    | '/integrations'
    | '/privacy-policy'
    | '/refund-return-policy'
    | '/solutions'
    | '/support'
    | '/terms-and-conditions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crm'
    | '/disclaimer'
    | '/features'
    | '/integrations'
    | '/privacy-policy'
    | '/refund-return-policy'
    | '/solutions'
    | '/support'
    | '/terms-and-conditions'
  id:
    | '__root__'
    | '/'
    | '/crm'
    | '/disclaimer'
    | '/features'
    | '/integrations'
    | '/privacy-policy'
    | '/refund-return-policy'
    | '/solutions'
    | '/support'
    | '/terms-and-conditions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrmRoute: typeof CrmRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FeaturesRoute: typeof FeaturesRoute
  IntegrationsRoute: typeof IntegrationsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundReturnPolicyRoute: typeof RefundReturnPolicyRoute
  SolutionsRoute: typeof SolutionsRoute
  SupportRoute: typeof SupportRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-return-policy': {
      id: '/refund-return-policy'
      path: '/refund-return-policy'
      fullPath: '/refund-return-policy'
      preLoaderRoute: typeof RefundReturnPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrmRoute: CrmRoute,
  DisclaimerRoute: DisclaimerRoute,
  FeaturesRoute: FeaturesRoute,
  IntegrationsRoute: IntegrationsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundReturnPolicyRoute: RefundReturnPolicyRoute,
  SolutionsRoute: SolutionsRoute,
  SupportRoute: SupportRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
